# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_remove_game_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='numCount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='viewedNumCount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
