# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0005_auto_20160731_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='clickCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
